### PR TITLE
updated index, style and main

### PR DESCRIPTION
**Pull request by Bhupesh-V**

### CODE REVIEW

**Comment by JonComo** [comment]
Have you tested this on the mac as well or only windows?

**Comment by Bhupesh-V** [comment]
Actually the original version you created was having issues on working on
windows correctly.
So i was thinking that we (or you) should create a new repo with the
windows compatible version
which i have created already ;)

**Comment by JonComo** [comment]
Hmm that's a pretty good idea, but I'd like to keep both versions on the same branch. Not too difficult to fix small differences for each OS I'd think?

**Comment by Bhupesh-V** [comment]
Yup u are right
So should i create another pull request
☺️☺️

**Pull request closed without merging**
