### PR TITLE
Revise matrix draw

### PR DESCRIPTION
**Pull request by catruge**
Hello. I noticed that the matrix drawn as the output from a textbox can have at most two dimensions:
NaN

It also squishes the content of the matrix if it doesn't fit:
Squished

This pull request implements a `MatrixOutput` class that supports wider strings, nested matrices, trimming of extra zeroes of matrix numbers and reusing matrices. It also starts using the class in `src/tools/text.js`, but not yet in `src/index.js`, and it hasn't been tested much, so I'm creating this pull request as a draft.

### CODE REVIEW

**Comment by JonComo** [comment]
Legendary! This will be useful for my deep learning series as well.. one of the main reasons I added support for rendering matrices.

**Comment by catruge** [comment]
@JonComo, thanks. Do you think that you could guide me with using it in the `vismult` function? I added functionality for calling a function before drawing an element (on `catruge:elementCallback`, but am not sure how exactly I should use it in `vismult`.

**Comment by JonComo** [comment]
@catruge Ah yeah vismult, I think that should just work with 1D and 2D matrices only. It's mainly for showing a neural network diagram next to the matrix multiply if I remember correctly. We would need to know the size of the matrices to lay them out correctly. Will your refactored matrix visualize code be able to give us the final width and height of the matrix?

**Comment by catruge** [comment]
Yes, the `MatrixOutput` class has `width` and `height` properties so that the nested matrices can be sized correctly.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by catruge** [comment]
@JonComo, yes, the `MatrixOutput` class has `width` and `height` properties so that the nested matrices can be sized correctly.

**Comment by catruge** [comment]
@JonComo, I incorporated it into `visdot` now. I was able to test it this time and it appears to be working.

**Comment by catruge** [comment]
@JonComo, I also got `vismult` to work and it seems to be working! It turns out I wasn't passing the arguments properly before.

**Comment by catruge** [comment]
@JonComo, on line 292 of `src/tools/text.js` (`drawBrackets(0, 0, size[0], size[1]);`), brackets are drawn with the same size as the split matrix numbers. The thing is, it's drawn in the top-left corner of the screen and can only remain for one frame. Should this code be removed, or will it be used in the future?

flashing brackets

**Comment by catruge** [comment]
Hello @JonComo. I noticed that matrices in textboxes are not split when they are one dimensional. I'll modify it so that it works with them too. If it was intentional, I'll revert the commit.

**Comment by catruge** [comment]
I merged `catruge:remove-brackets` into this branch for the time being.

**Comment by JonComo** [comment]
@catruge looks amazing! I'll merge and test as I'm on windows currently without git

**Pull request merged**
