### PR TITLE
Fix function-related errors

### PR DESCRIPTION
**Pull request by catruge**
Hello. This pull request should fix some ESLint function-related errors. It also refactors some related code, but that can be undone. The branch that this pull request would be merging is based off `catruge:no-undef` to prevent conflicts if a merge of both is attempted. If both this pull request and #46 are accepted, #46 should be merged first.

### CODE REVIEW

**Comment by JonComo** [comment]
@catruge Uh oh, I hope I didn't merge the pull requests out of order, I always try to start from oldest and work my way to newest. Is it easy enough to resolve these conflicts?

**Comment by catruge** [comment]
@JonComo, I just forgot that the formatting workflow would create a lot of conflicts. They should be pretty easy to fix.

**Comment by catruge** [comment]
Hello @JonComo. I wanted to mention that there should be a possibility to merge a squashed version of all the commits of a pull requests. That way, the project history isn't cluttered up with the merged commits.

**Comment by JonComo** [comment]
@catruge I tried the squash and merge, nice suggestion!

**Pull request merged**
