### PR TITLE
Smartly Evaluate Text Boxes

### PR DESCRIPTION
**Pull request by catruge**
The goal of this pull is to evaluate text boxes only when necessary to provide the correct output for the user, without substantially consuming the user's computer resources.

### CODE REVIEW

**Comment by catruge** [comment]
@JonComo, text boxes should now run only when necessary (although the required and modified variables must be specified like so: `{<requirements>}<expression>{<fulfilments>}`). The next step would be to determine the requirements and fulfilments from the parsed expression instead.

**Comment by catruge** [comment]
I noticed that `graph` and similar functions only draw to the screen once now, because the text boxes calling them are only evaluated once. This could be fixed by adding back the code which runs a text box each frame when prefixed with "e:", but there might be a better way that I don't know of.

**Comment by JonComo** [comment]
@catruge That sounds pretty clean! One improvement I was hoping to eventually make was to only graph once when the function the graph depended on changed. I suppose we'd have to graph in a different context and cache the result somehow? Might be less performant than just graphing over and over again as we currently do. Curious to hear your thoughts on that.

**Comment by catruge** [comment]
@JonComo, it's probably simplest to use the `Path2D` class (https://developer.mozilla.org/en-US/docs/Web/API/Path2D/Path2D) to redraw a cached version of the graph. We _could_ keep a canvas in JavaScript that's not added to the page and draw each graph on there instead, then copy it onto the visible canvas, but using `Path2D` will probably be cleaner.

**Comment by JonComo** [comment]
That looks good! I want to introduce coordinate system objects as well eventually.. little windows where you can put different graphs so you could graph a few different functions at the same time on different axes. For now lets try Path2d for the main graph.

**Comment by catruge** [comment]
OK then. Would it be easier to add the `Path2D` logic in another branch (either right now, or after merging this one once reviewed)?

**Comment by catruge** [comment]
I wanted to mention that function parameters are not added to the required variables list any more, so text boxes _should_ only be evaluated if actually necessary, although I might have missed a scenario where the code doesn't work.

I noticed that the cursor can now pass the boundaries of a text box. This seems to have been caused by 4fbb22c861fdbeb5191eb2fae3dbea81766e3825. I'll try fixing that now.

**Comment by JonComo** [comment]
@catruge could you give me an example of how expressions have to be written? {<requirements>}<expression>{<fulfilments>} seems too complicated on second thought. We should parse the expression and that would tell us what the requirements are.. and then if there is an equals symbol (assignment occuring) like x = y + 5 that would tell us that x is fulfilled by this text box. Is that what currently happens?

**Comment by catruge** [comment]
@JonComo, yes, `math.parse` is used to parse the expression and that is then used to determine the requirements and fulfilments. `{<requirements>}<expression>{<fulfilments>}` is still supported as a temporary workaround in case the automatic mechanism fails for whatever reason.

**Comment by JonComo** [comment]
@catruge :o wow that's amazing. Looks good then lets merge and I'll try it out. Excited!!

**Comment by catruge** [comment]
@JonComo, should I publish everything to GitHub Pages as version 2.0.0?

**Comment by JonComo** [comment]
Sounds good!

**Pull request merged**
